// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cursor.CloudAgents.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.V1.Secrets
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\secrets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SecretsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.V1.Secrets.SecretsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SecretsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/secrets{?cursor*,environmentId*,limit*,name*,repo*,scope*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.V1.Secrets.SecretsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SecretsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/secrets{?cursor*,environmentId*,limit*,name*,repo*,scope*}", rawUrl)
        {
        }
        /// <summary>
        /// List every Cloud Agents secret the API key can list, one item perversion, with the owner that holds it. No item includes a value.Without `scope` or `environmentId`, the list includes the team&apos;ssecrets and the user&apos;s personal secrets for an API key with norepository limit, and the secrets of the environments the key canlist. A team admin using their own user API key without `repo` alsogets the other members&apos; personal secrets and their personalenvironments&apos; secrets, without `repos`.Keep paging until `nextCursor` is `null`, and send the same filterswith each `cursor`.See https://cursor.com/docs/cloud-agent/api/endpoints#list-secrets.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ListSecretInventoryResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ListSecretInventoryResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Cursor.CloudAgents.OpenApiClient.V1.Secrets.SecretsRequestBuilder.SecretsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ListSecretInventoryResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Cursor.CloudAgents.OpenApiClient.V1.Secrets.SecretsRequestBuilder.SecretsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ListSecretInventoryResponse>(requestInfo, global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ListSecretInventoryResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List every Cloud Agents secret the API key can list, one item perversion, with the owner that holds it. No item includes a value.Without `scope` or `environmentId`, the list includes the team&apos;ssecrets and the user&apos;s personal secrets for an API key with norepository limit, and the secrets of the environments the key canlist. A team admin using their own user API key without `repo` alsogets the other members&apos; personal secrets and their personalenvironments&apos; secrets, without `repos`.Keep paging until `nextCursor` is `null`, and send the same filterswith each `cursor`.See https://cursor.com/docs/cloud-agent/api/endpoints#list-secrets.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Cursor.CloudAgents.OpenApiClient.V1.Secrets.SecretsRequestBuilder.SecretsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Cursor.CloudAgents.OpenApiClient.V1.Secrets.SecretsRequestBuilder.SecretsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.V1.Secrets.SecretsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.V1.Secrets.SecretsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.V1.Secrets.SecretsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List every Cloud Agents secret the API key can list, one item perversion, with the owner that holds it. No item includes a value.Without `scope` or `environmentId`, the list includes the team&apos;ssecrets and the user&apos;s personal secrets for an API key with norepository limit, and the secrets of the environments the key canlist. A team admin using their own user API key without `repo` alsogets the other members&apos; personal secrets and their personalenvironments&apos; secrets, without `repos`.Keep paging until `nextCursor` is `null`, and send the same filterswith each `cursor`.See https://cursor.com/docs/cloud-agent/api/endpoints#list-secrets.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SecretsRequestBuilderGetQueryParameters 
        {
            /// <summary>`nextCursor` from the previous page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>List only this environment&apos;s secrets. Can&apos;t be combined with`scope=team` or `scope=user`.</summary>
            [QueryParameter("environmentId")]
            public Guid? EnvironmentId { get; set; }
            /// <summary>Maximum items per page.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Only versions with this name, ignoring case.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            /// <summary>Only the versions an agent on this repository gets: versions forthat repository and versions for every repository.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("repo")]
            public string? Repo { get; set; }
#nullable restore
#else
            [QueryParameter("repo")]
            public string Repo { get; set; }
#endif
            /// <summary>`team` lists only the team&apos;s secrets, `user` only the user&apos;spersonal secrets, and `environment` only environment secrets.</summary>
            [QueryParameter("scope")]
            public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ListSecretsScopeParameter? Scope { get; set; }
        }
    }
}
#pragma warning restore CS0618
