// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.Item.Conversation
{
    /// <summary>Type of message - either from the user or the model</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConversationGetResponse_messages_type
    {
        [EnumMember(Value = "user_message")]
        #pragma warning disable CS1591
        User_message,
        #pragma warning restore CS1591
        [EnumMember(Value = "assistant_message")]
        #pragma warning disable CS1591
        Assistant_message,
        #pragma warning restore CS1591
    }
}
