// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents;
using Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Me;
using Soenneker.Cursor.CloudAgents.OpenApiClient.V0.ModelsRequests;
using Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Repositories;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.V0
{
    /// <summary>
    /// Builds and executes requests for operations under \v0
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V0RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The agents property</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsRequestBuilder Agents
        {
            get => new global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Me.MeRequestBuilder Me
        {
            get => new global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The models property</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.ModelsRequests.ModelsRequestBuilder Models
        {
            get => new global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.ModelsRequests.ModelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repositories property</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Repositories.RepositoriesRequestBuilder Repositories
        {
            get => new global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Repositories.RepositoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.V0RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V0RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.V0RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V0RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
