// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>
    /// Token usage summed across the returned runs.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AgentUsageResponseTotalUsage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Tokens read from cache.</summary>
        public int? CacheReadTokens { get; set; }
        /// <summary>Tokens written to cache.</summary>
        public int? CacheWriteTokens { get; set; }
        /// <summary>Input tokens consumed.</summary>
        public int? InputTokens { get; set; }
        /// <summary>Output tokens generated.</summary>
        public int? OutputTokens { get; set; }
        /// <summary>Sum of the four token counts above.</summary>
        public int? TotalTokens { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.AgentUsageResponseTotalUsage"/> and sets the default values.
        /// </summary>
        public AgentUsageResponseTotalUsage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.AgentUsageResponseTotalUsage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.AgentUsageResponseTotalUsage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.AgentUsageResponseTotalUsage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cacheReadTokens", n => { CacheReadTokens = n.GetIntValue(); } },
                { "cacheWriteTokens", n => { CacheWriteTokens = n.GetIntValue(); } },
                { "inputTokens", n => { InputTokens = n.GetIntValue(); } },
                { "outputTokens", n => { OutputTokens = n.GetIntValue(); } },
                { "totalTokens", n => { TotalTokens = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("cacheReadTokens", CacheReadTokens);
            writer.WriteIntValue("cacheWriteTokens", CacheWriteTokens);
            writer.WriteIntValue("inputTokens", InputTokens);
            writer.WriteIntValue("outputTokens", OutputTokens);
            writer.WriteIntValue("totalTokens", TotalTokens);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
