// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Agent : global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.AgentSummary, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Whether Cursor opens a pull request when the run completes.</summary>
        public bool? AutoCreatePR { get; set; }
        /// <summary>Custom subagents defined at create time. Omitted when none were provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagent>? CustomSubagents { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagent> CustomSubagents { get; set; }
#endif
        /// <summary>Repository configuration. Empty for no-repo agents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.RepoConfig>? Repos { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.RepoConfig> Repos { get; set; }
#endif
        /// <summary>Whether to skip requesting the user as a reviewer when Cursor opens a PR.</summary>
        public bool? SkipReviewerRequest { get; set; }
        /// <summary>When `false` (the default), Cursor pushes commits to a new auto-generated branch. When `true`, commits land on the existing head branch.</summary>
        public bool? WorkOnCurrentBranch { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Agent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Agent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.Agent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "autoCreatePR", n => { AutoCreatePR = n.GetBoolValue(); } },
                { "customSubagents", n => { CustomSubagents = n.GetCollectionOfObjectValues<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagent>(global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagent.CreateFromDiscriminatorValue)?.AsList(); } },
                { "repos", n => { Repos = n.GetCollectionOfObjectValues<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.RepoConfig>(global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.RepoConfig.CreateFromDiscriminatorValue)?.AsList(); } },
                { "skipReviewerRequest", n => { SkipReviewerRequest = n.GetBoolValue(); } },
                { "workOnCurrentBranch", n => { WorkOnCurrentBranch = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteBoolValue("autoCreatePR", AutoCreatePR);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagent>("customSubagents", CustomSubagents);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.RepoConfig>("repos", Repos);
            writer.WriteBoolValue("skipReviewerRequest", SkipReviewerRequest);
            writer.WriteBoolValue("workOnCurrentBranch", WorkOnCurrentBranch);
        }
    }
}
#pragma warning restore CS0618
