// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>Conversation mode. `plan` explores and drafts a plan before coding; `agent` implements changes directly. On follow-up runs, omit to keep the conversation&apos;s current mode; set explicitly to switch modes for that run.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentMode
    {
        [EnumMember(Value = "agent")]
        #pragma warning disable CS1591
        Agent,
        #pragma warning restore CS1591
        [EnumMember(Value = "plan")]
        #pragma warning disable CS1591
        Plan,
        #pragma warning restore CS1591
    }
}
