// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>Agent lifecycle state. Execution status lives on runs.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentSummaryStatus
    {
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "ARCHIVED")]
        #pragma warning disable CS1591
        Archived,
        #pragma warning restore CS1591
    }
}
