// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>Execution environment type. `cloud` uses Cursor-hosted VMs; `pool` and `machine` route to self-hosted workers.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentEnvType
    {
        [EnumMember(Value = "cloud")]
        #pragma warning disable CS1591
        Cloud,
        #pragma warning restore CS1591
        [EnumMember(Value = "pool")]
        #pragma warning disable CS1591
        Pool,
        #pragma warning restore CS1591
        [EnumMember(Value = "machine")]
        #pragma warning disable CS1591
        Machine,
        #pragma warning restore CS1591
    }
}
