// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiKeyInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Display name of the API key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiKeyName { get; set; }
#nullable restore
#else
        public string ApiKeyName { get; set; }
#endif
        /// <summary>When the API key was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Email of the API key&apos;s owner. Omitted for service-account / team API keys.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserEmail { get; set; }
#nullable restore
#else
        public string UserEmail { get; set; }
#endif
        /// <summary>First name of the API key&apos;s owner, when populated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserFirstName { get; set; }
#nullable restore
#else
        public string UserFirstName { get; set; }
#endif
        /// <summary>Numeric Cursor user ID of the API key&apos;s owner. Omitted for service-account / team API keys, which aren&apos;t tied to a specific user.</summary>
        public int? UserId { get; set; }
        /// <summary>Last name of the API key&apos;s owner, when populated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserLastName { get; set; }
#nullable restore
#else
        public string UserLastName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ApiKeyInfo"/> and sets the default values.
        /// </summary>
        public ApiKeyInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ApiKeyInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ApiKeyInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ApiKeyInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apiKeyName", n => { ApiKeyName = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "userEmail", n => { UserEmail = n.GetStringValue(); } },
                { "userFirstName", n => { UserFirstName = n.GetStringValue(); } },
                { "userId", n => { UserId = n.GetIntValue(); } },
                { "userLastName", n => { UserLastName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("apiKeyName", ApiKeyName);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("userEmail", UserEmail);
            writer.WriteStringValue("userFirstName", UserFirstName);
            writer.WriteIntValue("userId", UserId);
            writer.WriteStringValue("userLastName", UserLastName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
