// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BuildType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "build")]
        #pragma warning disable CS1591
        Build,
        #pragma warning restore CS1591
    }
}
