// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>`personal` creates an environment for the API key&apos;s user, and `team` creates one for the team.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateEnvironmentRequestOwner
    {
        [EnumMember(Value = "personal")]
        #pragma warning disable CS1591
        Personal,
        #pragma warning restore CS1591
        [EnumMember(Value = "team")]
        #pragma warning disable CS1591
        Team,
        #pragma warning restore CS1591
    }
}
