// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateEnvironmentRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The environment&apos;s `environment.json`, as a JSON-encoded string, using the same schema as a `.cursor/environment.json` file. An invalid configuration returns `400 validation_error`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvironmentJson { get; set; }
#nullable restore
#else
        public string EnvironmentJson { get; set; }
#endif
        /// <summary>Display name. It must differ from the names of the owner&apos;s other environments; a name the owner already uses returns `409 environment_name_conflict`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>`personal` creates an environment for the API key&apos;s user, and `team` creates one for the team.</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CreateEnvironmentRequestOwner? Owner { get; set; }
        /// <summary>Repositories for the environment, or an empty array for an environment without repositories. Cursor must be able to reach each one through your source control integration; otherwise the request returns `400 repository_access`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentRepo>? Repos { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentRepo> Repos { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CreateEnvironmentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CreateEnvironmentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CreateEnvironmentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "environmentJson", n => { EnvironmentJson = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CreateEnvironmentRequestOwner>(); } },
                { "repos", n => { Repos = n.GetCollectionOfObjectValues<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentRepo>(global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentRepo.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("environmentJson", EnvironmentJson);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CreateEnvironmentRequestOwner>("owner", Owner);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentRepo>("repos", Repos);
        }
    }
}
#pragma warning restore CS0618
