// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateAgentRequest_target : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to create a new branch (true) or use the PR&apos;s existing head branch (false). Only applies when source.prUrl is provided.</summary>
        public bool? AutoBranch { get; set; }
        /// <summary>Whether to automatically create a pull request when the agent completes</summary>
        public bool? AutoCreatePr { get; set; }
        /// <summary>Custom branch name for the agent to create</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BranchName { get; set; }
#nullable restore
#else
        public string BranchName { get; set; }
#endif
        /// <summary>Whether to open the pull request as the Cursor GitHub App instead of as the user. Only applies if autoCreatePr is true.</summary>
        public bool? OpenAsCursorGithubApp { get; set; }
        /// <summary>Whether to skip adding the user as a reviewer to the pull request. Only applies if autoCreatePr is true and the PR is opened as the Cursor GitHub App.</summary>
        public bool? SkipReviewerRequest { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CreateAgentRequest_target"/> and sets the default values.
        /// </summary>
        public CreateAgentRequest_target()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CreateAgentRequest_target"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CreateAgentRequest_target CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CreateAgentRequest_target();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoBranch", n => { AutoBranch = n.GetBoolValue(); } },
                { "autoCreatePr", n => { AutoCreatePr = n.GetBoolValue(); } },
                { "branchName", n => { BranchName = n.GetStringValue(); } },
                { "openAsCursorGithubApp", n => { OpenAsCursorGithubApp = n.GetBoolValue(); } },
                { "skipReviewerRequest", n => { SkipReviewerRequest = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("autoBranch", AutoBranch);
            writer.WriteBoolValue("autoCreatePr", AutoCreatePr);
            writer.WriteStringValue("branchName", BranchName);
            writer.WriteBoolValue("openAsCursorGithubApp", OpenAsCursorGithubApp);
            writer.WriteBoolValue("skipReviewerRequest", SkipReviewerRequest);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
