// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>Use the parent agent&apos;s model selection.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomSubagentModelWrapperValue
    {
        [EnumMember(Value = "inherit")]
        #pragma warning disable CS1591
        Inherit,
        #pragma warning restore CS1591
    }
}
