// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModelBranch2"/>, <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModelWrapper"/>, <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ModelRef"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomSubagentModel : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModelBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModelBranch2? CustomSubagentModelBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModelBranch2 CustomSubagentModelBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModelWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModelWrapper? CustomSubagentModelWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModelWrapper CustomSubagentModelWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ModelRef"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ModelRef? ModelRef { get; set; }
#nullable restore
#else
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ModelRef ModelRef { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModel();
            if("CustomSubagentModel_2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CustomSubagentModelBranch2 = new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModelBranch2();
            }
            else if("ModelRef".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ModelRef = new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ModelRef();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CustomSubagentModelBranch2 != null)
            {
                return CustomSubagentModelBranch2.GetFieldDeserializers();
            }
            else if(CustomSubagentModelWrapper != null)
            {
                return CustomSubagentModelWrapper.GetFieldDeserializers();
            }
            else if(ModelRef != null)
            {
                return ModelRef.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CustomSubagentModelBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModelBranch2>(null, CustomSubagentModelBranch2);
            }
            else if(CustomSubagentModelWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.CustomSubagentModelWrapper>(null, CustomSubagentModelWrapper);
            }
            else if(ModelRef != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.ModelRef>(null, ModelRef);
            }
        }
    }
}
#pragma warning restore CS0618
