// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>What started the build. `RECURRING` for a scheduled build, `CONFIG_CHANGE` after a configuration or secrets change, or `MANUAL` for one started on request.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnvironmentBuildTrigger
    {
        [EnumMember(Value = "RECURRING")]
        #pragma warning disable CS1591
        Recurring,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONFIG_CHANGE")]
        #pragma warning disable CS1591
        ConfigChange,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANUAL")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
    }
}
