// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>Where the change came from.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnvironmentHistoryEventSource
    {
        [EnumMember(Value = "dashboard")]
        #pragma warning disable CS1591
        Dashboard,
        #pragma warning restore CS1591
        [EnumMember(Value = "setup_flow")]
        #pragma warning disable CS1591
        SetupFlow,
        #pragma warning restore CS1591
        [EnumMember(Value = "restore")]
        #pragma warning disable CS1591
        Restore,
        #pragma warning restore CS1591
        [EnumMember(Value = "api")]
        #pragma warning disable CS1591
        Api,
        #pragma warning restore CS1591
        [EnumMember(Value = "agent_run")]
        #pragma warning disable CS1591
        AgentRun,
        #pragma warning restore CS1591
        [EnumMember(Value = "repo_file")]
        #pragma warning disable CS1591
        RepoFile,
        #pragma warning restore CS1591
        [EnumMember(Value = "request_override")]
        #pragma warning disable CS1591
        RequestOverride,
        #pragma warning restore CS1591
    }
}
