// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EnvironmentHistoryEvent : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>When the change was made.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>`true` for the event that saved the environment&apos;s current configuration.</summary>
        public bool? Current { get; set; }
        /// <summary>The event&apos;s details, as the History tab shows them.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The `environment.json` the event saved, as a JSON-encoded string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvironmentJson { get; set; }
#nullable restore
#else
        public string EnvironmentJson { get; set; }
#endif
        /// <summary>Unique event identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The kind property</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentHistoryEventKind? Kind { get; set; }
        /// <summary>Where the change came from.</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentHistoryEventSource? Source { get; set; }
        /// <summary>The event&apos;s summary, as the History tab shows it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentHistoryEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentHistoryEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentHistoryEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "current", n => { Current = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "environmentJson", n => { EnvironmentJson = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentHistoryEventKind>(); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentHistoryEventSource>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteBoolValue("current", Current);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("environmentJson", EnvironmentJson);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentHistoryEventKind>("kind", Kind);
            writer.WriteEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentHistoryEventSource>("source", Source);
            writer.WriteStringValue("title", Title);
        }
    }
}
#pragma warning restore CS0618
