// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EnvironmentHistoryEventKind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "created")]
        #pragma warning disable CS1591
        Created,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated")]
        #pragma warning disable CS1591
        Updated,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "backfilled")]
        #pragma warning disable CS1591
        Backfilled,
        #pragma warning restore CS1591
        [EnumMember(Value = "changed")]
        #pragma warning disable CS1591
        Changed,
        #pragma warning restore CS1591
    }
}
