// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EnvironmentBuild : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>When the build finished. Omitted while it&apos;s in progress.</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>When the build was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>`true` for a draft build. Agents don&apos;t start from a draft build until it&apos;s activated.</summary>
        public bool? Draft { get; set; }
        /// <summary>ID of the environment the build belongs to.</summary>
        public Guid? EnvironmentId { get; set; }
        /// <summary>Why a failed build failed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuildFailure? Failure { get; set; }
#nullable restore
#else
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuildFailure Failure { get; set; }
#endif
        /// <summary>Unique build identifier, in the form `bld-YYYYMMDD-&lt;uuid&gt;`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Build status. A skipped build found nothing to rebuild.</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuildStatus? Status { get; set; }
        /// <summary>What started the build. `RECURRING` for a scheduled build, `CONFIG_CHANGE` after a configuration or secrets change, or `MANUAL` for one started on request.</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuildTrigger? Trigger { get; set; }
        /// <summary>When the build was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuild"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuild CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuild();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completedAt", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "draft", n => { Draft = n.GetBoolValue(); } },
                { "environmentId", n => { EnvironmentId = n.GetGuidValue(); } },
                { "failure", n => { Failure = n.GetObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuildFailure>(global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuildFailure.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuildStatus>(); } },
                { "trigger", n => { Trigger = n.GetEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuildTrigger>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completedAt", CompletedAt);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteBoolValue("draft", Draft);
            writer.WriteGuidValue("environmentId", EnvironmentId);
            writer.WriteObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuildFailure>("failure", Failure);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuildStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentBuildTrigger>("trigger", Trigger);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
        }
    }
}
#pragma warning restore CS0618
