// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>Build status. A skipped build found nothing to rebuild.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnvironmentBuildStatus
    {
        [EnumMember(Value = "IN_PROGRESS")]
        #pragma warning disable CS1591
        InProgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUCCEEDED")]
        #pragma warning disable CS1591
        Succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "SKIPPED")]
        #pragma warning disable CS1591
        Skipped,
        #pragma warning restore CS1591
    }
}
