// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>`INSTALL_FAILED` when the `install` command failed, or `TERMINAL_FAILURE` for other failures.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnvironmentBuildFailureType
    {
        [EnumMember(Value = "INSTALL_FAILED")]
        #pragma warning disable CS1591
        InstallFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "TERMINAL_FAILURE")]
        #pragma warning disable CS1591
        TerminalFailure,
        #pragma warning restore CS1591
    }
}
