// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromBuild"/>, <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromUniversalImage"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnvironmentActiveBuild : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromBuild"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromBuild? EnvironmentActiveBuildFromBuild { get; set; }
#nullable restore
#else
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromBuild EnvironmentActiveBuildFromBuild { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromUniversalImage"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromUniversalImage? EnvironmentActiveBuildFromUniversalImage { get; set; }
#nullable restore
#else
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromUniversalImage EnvironmentActiveBuildFromUniversalImage { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuild"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuild CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuild();
            if("build".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EnvironmentActiveBuildFromBuild = new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromBuild();
            }
            else if("EnvironmentActiveBuildFromUniversalImage".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EnvironmentActiveBuildFromUniversalImage = new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromUniversalImage();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(EnvironmentActiveBuildFromBuild != null)
            {
                return EnvironmentActiveBuildFromBuild.GetFieldDeserializers();
            }
            else if(EnvironmentActiveBuildFromUniversalImage != null)
            {
                return EnvironmentActiveBuildFromUniversalImage.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(EnvironmentActiveBuildFromBuild != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromBuild>(null, EnvironmentActiveBuildFromBuild);
            }
            else if(EnvironmentActiveBuildFromUniversalImage != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.EnvironmentActiveBuildFromUniversalImage>(null, EnvironmentActiveBuildFromUniversalImage);
            }
        }
    }
}
#pragma warning restore CS0618
