// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>
    /// A secret version with the owner that holds it. Responses neverinclude a secret&apos;s value.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InventorySecretVersion : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When the version was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The version ID its owner&apos;s own list shows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Environment variable name agents see.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Who holds a secret version: `team` for the team the API key worksin, `user` for a user&apos;s personal secrets, or `environment` for anenvironment&apos;s secrets.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.SecretInventoryOwner? Owner { get; set; }
#nullable restore
#else
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.SecretInventoryOwner Owner { get; set; }
#endif
        /// <summary>The only repositories that get this version, or empty when everyrepository gets it. Every version has it, including othermembers&apos; versions in a team admin&apos;s list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Repos { get; set; }
#nullable restore
#else
        public List<string> Repos { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.InventorySecretVersionType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.InventorySecretVersion"/> and sets the default values.
        /// </summary>
        public InventorySecretVersion()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.InventorySecretVersion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.InventorySecretVersion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.InventorySecretVersion();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.SecretInventoryOwner>(global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.SecretInventoryOwner.CreateFromDiscriminatorValue); } },
                { "repos", n => { Repos = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.InventorySecretVersionType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.SecretInventoryOwner>("owner", Owner);
            writer.WriteCollectionOfPrimitiveValues<string>("repos", Repos);
            writer.WriteEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.InventorySecretVersionType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
