// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InventorySecretVersionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "runtime_secret")]
        #pragma warning disable CS1591
        RuntimeSecret,
        #pragma warning restore CS1591
        [EnumMember(Value = "environment_variable")]
        #pragma warning disable CS1591
        EnvironmentVariable,
        #pragma warning restore CS1591
        [EnumMember(Value = "build_secret")]
        #pragma warning disable CS1591
        BuildSecret,
        #pragma warning restore CS1591
    }
}
