// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>Remote MCP transport. Defaults to `http` when `url` is provided.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RemoteMcpServer_type
    {
        [EnumMember(Value = "http")]
        #pragma warning disable CS1591
        Http,
        #pragma warning restore CS1591
        [EnumMember(Value = "sse")]
        #pragma warning disable CS1591
        Sse,
        #pragma warning restore CS1591
    }
}
