// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>Current run status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Run_status
    {
        [EnumMember(Value = "CREATING")]
        #pragma warning disable CS1591
        CREATING,
        #pragma warning restore CS1591
        [EnumMember(Value = "RUNNING")]
        #pragma warning disable CS1591
        RUNNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINISHED")]
        #pragma warning disable CS1591
        FINISHED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        CANCELLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        EXPIRED,
        #pragma warning restore CS1591
    }
}
