// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>Current run status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RunStatus
    {
        [EnumMember(Value = "CREATING")]
        #pragma warning disable CS1591
        Creating,
        #pragma warning restore CS1591
        [EnumMember(Value = "RUNNING")]
        #pragma warning disable CS1591
        Running,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINISHED")]
        #pragma warning disable CS1591
        Finished,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
    }
}
