// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>A new version defaults to `runtime_secret`. A change without`type` keeps the version&apos;s type. Build Secrets can&apos;t be setthrough the API yet.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SetSecretRequestType
    {
        [EnumMember(Value = "runtime_secret")]
        #pragma warning disable CS1591
        RuntimeSecret,
        #pragma warning restore CS1591
        [EnumMember(Value = "environment_variable")]
        #pragma warning disable CS1591
        EnvironmentVariable,
        #pragma warning restore CS1591
    }
}
