// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    /// <summary>Stdio MCP server. Defaults to `stdio` when `command` is provided.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StdioMcpServer_type
    {
        [EnumMember(Value = "stdio")]
        #pragma warning disable CS1591
        Stdio,
        #pragma warning restore CS1591
    }
}
