// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StdioMcpServer : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Command arguments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Args { get; set; }
#nullable restore
#else
        public List<string> Args { get; set; }
#endif
        /// <summary>Command to start inside the cloud agent VM.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Command { get; set; }
#nullable restore
#else
        public string Command { get; set; }
#endif
        /// <summary>Environment variables passed to the stdio MCP server inside the VM.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.StdioMcpServerEnvProperty? Env { get; set; }
#nullable restore
#else
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.StdioMcpServerEnvProperty Env { get; set; }
#endif
        /// <summary>MCP server name exposed to the agent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Stdio MCP server. Defaults to `stdio` when `command` is provided.</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.StdioMcpServerType? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.StdioMcpServer"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.StdioMcpServer CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.StdioMcpServer();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "args", n => { Args = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "command", n => { Command = n.GetStringValue(); } },
                { "env", n => { Env = n.GetObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.StdioMcpServerEnvProperty>(global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.StdioMcpServerEnvProperty.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.StdioMcpServerType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("args", Args);
            writer.WriteStringValue("command", Command);
            writer.WriteObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.StdioMcpServerEnvProperty>("env", Env);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.Models.StdioMcpServerType>("type", Type);
        }
    }
}
#pragma warning restore CS0618
