// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentsGetResponse_agents : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When the agent was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Unique identifier for the cloud agent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Name for the agent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_source? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_source Source { get; set; }
#endif
        /// <summary>Current status of the cloud agent</summary>
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_status? Status { get; set; }
        /// <summary>Summary of the agent&apos;s work</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>The target property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_target? Target { get; set; }
#nullable restore
#else
        public global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_target Target { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents"/> and sets the default values.
        /// </summary>
        public AgentsGetResponse_agents()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_source>(global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_source.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_status>(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "target", n => { Target = n.GetObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_target>(global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_target.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_source>("source", Source);
            writer.WriteEnumValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_status>("status", Status);
            writer.WriteStringValue("summary", Summary);
            writer.WriteObjectValue<global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsGetResponse_agents_target>("target", Target);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
