// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentsPostResponse_target : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether a pull request will be automatically created</summary>
        public bool? AutoCreatePr { get; set; }
        /// <summary>The Git branch name where the agent is working</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BranchName { get; set; }
#nullable restore
#else
        public string BranchName { get; set; }
#endif
        /// <summary>Whether the pull request will be opened as the Cursor GitHub App</summary>
        public bool? OpenAsCursorGithubApp { get; set; }
        /// <summary>URL of the pull request, if agent was created from a PR</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrUrl { get; set; }
#nullable restore
#else
        public string PrUrl { get; set; }
#endif
        /// <summary>Whether to skip adding the user as a reviewer to the pull request</summary>
        public bool? SkipReviewerRequest { get; set; }
        /// <summary>URL to view the agent in Cursor Web</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsPostResponse_target"/> and sets the default values.
        /// </summary>
        public AgentsPostResponse_target()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsPostResponse_target"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsPostResponse_target CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents.AgentsPostResponse_target();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoCreatePr", n => { AutoCreatePr = n.GetBoolValue(); } },
                { "branchName", n => { BranchName = n.GetStringValue(); } },
                { "openAsCursorGithubApp", n => { OpenAsCursorGithubApp = n.GetBoolValue(); } },
                { "prUrl", n => { PrUrl = n.GetStringValue(); } },
                { "skipReviewerRequest", n => { SkipReviewerRequest = n.GetBoolValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("autoCreatePr", AutoCreatePr);
            writer.WriteStringValue("branchName", BranchName);
            writer.WriteBoolValue("openAsCursorGithubApp", OpenAsCursorGithubApp);
            writer.WriteStringValue("prUrl", PrUrl);
            writer.WriteBoolValue("skipReviewerRequest", SkipReviewerRequest);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
