// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cursor.CloudAgents.OpenApiClient.V0.Agents
{
    /// <summary>Initial status of the newly created agent</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentsPostResponse_status
    {
        [EnumMember(Value = "CREATING")]
        #pragma warning disable CS1591
        CREATING,
        #pragma warning restore CS1591
    }
}
